 ---
 kind: template
 apiVersion: v1
 metadata:
    name: python-task-service
objects:
-
 apiVersion: apps/v1
    kind: Deployment
    metadata:
        name: python-sample
        labels:
            app: python-sample
    spec:
      selector:
        matchLabels:
          app: python-sample
      template:
        metadata:
          labels:
            app: python-sample
        spec:
          containers:
          - image: dockerhub.cisco.com/constellation-houston-docker-dev/python-sample:test3
            name: python-sample
            ports:
            - containerPort: 3333
-
    apiVersion: v1
    kind: Service
    metadata:
        name: python-sample
        labels:
            app: python-sample
            name: python-sample
    spec:
      ports:
        - port: 80
          protocol: TCP
          targetPort: 3333
      selector:
        app: python-sample
      type: NodePort
---