apiVersion: v1
kind: List
items:
-
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: mongo
  name: mongo
spec:
  #serviceName: database
  replicas: 1
  selector:
    matchLabels:
      name: mongo
  template:
    metadata:
      labels:
        name: mongo
      name: mongo
    spec:
      containers:
      - name: mongo
        image: mongo
        ports:
        - name: mongo
          containerPort: 27017
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: administrator
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: wvbDjPOAXRlUEqRm
-
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    name: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo